// <auto-generated />
using System;
using Amplifund.Assignment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Amplifund.Assignment.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241003184215_SeedStates")]
    partial class SeedStates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Amplifund.Assignment.Domain.Entities.Common.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AL",
                            Name = "Alabama"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AK",
                            Name = "Alaska"
                        },
                        new
                        {
                            Id = 3,
                            Code = "AZ",
                            Name = "Arizona"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AR",
                            Name = "Arkansas"
                        },
                        new
                        {
                            Id = 5,
                            Code = "CA",
                            Name = "California"
                        },
                        new
                        {
                            Id = 6,
                            Code = "CO",
                            Name = "Colorado"
                        },
                        new
                        {
                            Id = 7,
                            Code = "CT",
                            Name = "Connecticut"
                        },
                        new
                        {
                            Id = 8,
                            Code = "DE",
                            Name = "Delaware"
                        },
                        new
                        {
                            Id = 9,
                            Code = "FL",
                            Name = "Florida"
                        },
                        new
                        {
                            Id = 10,
                            Code = "GA",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 11,
                            Code = "HI",
                            Name = "Hawaii"
                        },
                        new
                        {
                            Id = 12,
                            Code = "ID",
                            Name = "Idaho"
                        },
                        new
                        {
                            Id = 13,
                            Code = "IL",
                            Name = "Illinois"
                        },
                        new
                        {
                            Id = 14,
                            Code = "IN",
                            Name = "Indiana"
                        },
                        new
                        {
                            Id = 15,
                            Code = "IA",
                            Name = "Iowa"
                        },
                        new
                        {
                            Id = 16,
                            Code = "KS",
                            Name = "Kansas"
                        },
                        new
                        {
                            Id = 17,
                            Code = "KY",
                            Name = "Kentucky"
                        },
                        new
                        {
                            Id = 18,
                            Code = "LA",
                            Name = "Louisiana"
                        },
                        new
                        {
                            Id = 19,
                            Code = "ME",
                            Name = "Maine"
                        },
                        new
                        {
                            Id = 20,
                            Code = "MD",
                            Name = "Maryland"
                        },
                        new
                        {
                            Id = 21,
                            Code = "MA",
                            Name = "Massachusetts"
                        },
                        new
                        {
                            Id = 22,
                            Code = "MI",
                            Name = "Michigan"
                        },
                        new
                        {
                            Id = 23,
                            Code = "MN",
                            Name = "Minnesota"
                        },
                        new
                        {
                            Id = 24,
                            Code = "MS",
                            Name = "Mississippi"
                        },
                        new
                        {
                            Id = 25,
                            Code = "MO",
                            Name = "Missouri"
                        },
                        new
                        {
                            Id = 26,
                            Code = "MT",
                            Name = "Montana"
                        },
                        new
                        {
                            Id = 27,
                            Code = "NE",
                            Name = "Nebraska"
                        },
                        new
                        {
                            Id = 28,
                            Code = "NV",
                            Name = "Nevada"
                        },
                        new
                        {
                            Id = 29,
                            Code = "NH",
                            Name = "New Hampshire"
                        },
                        new
                        {
                            Id = 30,
                            Code = "NJ",
                            Name = "New Jersey"
                        },
                        new
                        {
                            Id = 31,
                            Code = "NM",
                            Name = "New Mexico"
                        },
                        new
                        {
                            Id = 32,
                            Code = "NY",
                            Name = "New York"
                        },
                        new
                        {
                            Id = 33,
                            Code = "NC",
                            Name = "North Carolina"
                        },
                        new
                        {
                            Id = 34,
                            Code = "ND",
                            Name = "North Dakota"
                        },
                        new
                        {
                            Id = 35,
                            Code = "OH",
                            Name = "Ohio"
                        },
                        new
                        {
                            Id = 36,
                            Code = "OK",
                            Name = "Oklahoma"
                        },
                        new
                        {
                            Id = 37,
                            Code = "OR",
                            Name = "Oregon"
                        },
                        new
                        {
                            Id = 38,
                            Code = "PA",
                            Name = "Pennsylvania"
                        },
                        new
                        {
                            Id = 39,
                            Code = "RI",
                            Name = "Rhode Island"
                        },
                        new
                        {
                            Id = 40,
                            Code = "SC",
                            Name = "South Carolina"
                        },
                        new
                        {
                            Id = 41,
                            Code = "SD",
                            Name = "South Dakota"
                        },
                        new
                        {
                            Id = 42,
                            Code = "TN",
                            Name = "Tennessee"
                        },
                        new
                        {
                            Id = 43,
                            Code = "TX",
                            Name = "Texas"
                        },
                        new
                        {
                            Id = 44,
                            Code = "UT",
                            Name = "Utah"
                        },
                        new
                        {
                            Id = 45,
                            Code = "VT",
                            Name = "Vermont"
                        },
                        new
                        {
                            Id = 46,
                            Code = "VA",
                            Name = "Virginia"
                        },
                        new
                        {
                            Id = 47,
                            Code = "WA",
                            Name = "Washington"
                        },
                        new
                        {
                            Id = 48,
                            Code = "WV",
                            Name = "West Virginia"
                        },
                        new
                        {
                            Id = 49,
                            Code = "WI",
                            Name = "Wisconsin"
                        },
                        new
                        {
                            Id = 50,
                            Code = "WY",
                            Name = "Wyoming"
                        });
                });

            modelBuilder.Entity("Amplifund.Assignment.Domain.Entities.Grant.Grant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Grant");
                });

            modelBuilder.Entity("Amplifund.Assignment.Domain.Entities.Grant.StateGrant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("GrantId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GrantId");

                    b.HasIndex("StateId");

                    b.ToTable("StateGrant");
                });

            modelBuilder.Entity("Amplifund.Assignment.Domain.Entities.Grant.StateGrant", b =>
                {
                    b.HasOne("Amplifund.Assignment.Domain.Entities.Grant.Grant", "Grant")
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amplifund.Assignment.Domain.Entities.Common.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grant");

                    b.Navigation("State");
                });
#pragma warning restore 612, 618
        }
    }
}
